{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "9d2ad873_ef043411",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1693933
      },
      "writtenOn": "2024-06-18T03:16:43Z",
      "side": 1,
      "message": "@sadiqsada@google.com I think this can resolve your issue in https://b.corp.google.com/issues/332765270#comment12",
      "revId": "ed9879b4f8241090fb3b21b1bbe029d86004f345",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "4c05b442_c6f4ca3a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1960475
      },
      "writtenOn": "2024-06-18T21:26:51Z",
      "side": 1,
      "message": "I can\u0027t run the test from main with this change. I\u0027m getting the same error. But I can run the test from udc-tv-dev since I had to fast-forward this project (ag/27061515) on udc-tv-dev to enable thread. Test Result: b/332765270#comment13",
      "parentUuid": "9d2ad873_ef043411",
      "revId": "ed9879b4f8241090fb3b21b1bbe029d86004f345",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}